name: Docker Image

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get the version
      id: vars
      run: |
        echo ::set-output name=VERSION::$(date +%Y%m%d)-${GITHUB_SHA::7}
        echo ::set-output name=TAG_PREFIX::docker.pkg.github.com/alekmarinov/aquaponics/aquaponics
    - name: Build the image
      run: |
        docker build \
        --tag ${{steps.vars.outputs.TAG_PREFIX}}:${{steps.vars.outputs.VERSION}} \
        --tag ${{steps.vars.outputs.TAG_PREFIX}}:latest \
        src/
    - name: Docker Login
      uses: azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com
        username: $GITHUB_ACTOR
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Docker Push
      run: >
        docker push ${{steps.vars.outputs.TAG_PREFIX}}:${{steps.vars.outputs.VERSION}} ${{steps.vars.outputs.TAG_PREFIX}}:latest
